name: run main.py

on:
  push:
    branches: ["main"]
jobs:
  # build:
  #   runs-on: ${{matrix.os}}
  #   strategy:
  #     matrix:
  #       # os: [ubuntu-latest, macos-latest, windows-latest]
  #       os: [ubuntu-latest]
  #       python-version: ['3.12', '3.11', '3.10', '3.9']
  #   name: Checking with different python Version ${{matrix.python-version}} sample
  #   steps:
  #     - name: checkout repo content
  #       uses: actions/checkout@v3 # checkout the repository content to github runner

  #     - name: setup python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{matrix.python-version}} # install the python version needed
  #         # python-version: '3.11' # install the python version needed
  #         # python-version: ${{matrix.python-version}} # install the python version needed
          
  #     - name: install python packages
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
      
  #     - name: Display Python Version
  #       run: python --version
      
  #     - name: Display System info
  #       run: |
  #         echo "System info"
  #         echo "-----------"
  #         echo "OS: ${{matrix.os}}"
  #         echo "Python Version: ${{matrix.python-version}}"
  #         echo "-----------"
          
  #     - name: execute py script # run main.py
  #       run: python tracker.py
  deploy:
    # needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: ['3.12', '3.11', '3.10', '3.9']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install setuptools wheel twine
    - name: Build package
      run: python -m build
    - name: Build wheels
      run: |
          python setup.py sdist bdist_wheel --name "tracker" --version "0.0.1" --python-tag "py3" --pythons "3.9" "3.10" "3.11" "3.12"
    - name: Store Wheel on GitHub
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist
    - name: Publish package
      run: echo "Not publishing package"